services:

  mysql: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    ports:
      - "3306:3306"   
    networks:
      - ambiente-network 

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node  
    restart: always
    tty: true  
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - ambiente-network   

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    tty: true    
    ports:
      - "8080:80"    
    depends_on:
      - node
    networks:
      - ambiente-network  
    
networks:
  ambiente-network:
    driver: bridge
    